spring:
    http.multipart:
        max-file-size: 128MB
        max-request-size: 128MB

    datasource:
        url: jdbc:mysql://localhost:3306/parser_db?createDatabaseIfNotExist=true
        username: root
        password:

    jpa.hibernate.ddl-auto: update

logging.level:
    com.mariana: DEBUG

parser.concurrent.threads: 3
